# golangci-lint configuration for ForgeUI
# Production-ready linting configuration with strict settings

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  print-linter-name: true
  print-issued-lines: true

linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/docs/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: none
  # Enable specific linter.
  enable:
    - arangolint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    # - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    # - depguard
    - dogsled
    # - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    # - forcetypeassert
    # - funcorder
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - godoclint
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    # - iface
    - importas
    - inamedparam
    - ineffassign
    # - interfacebloat
    - intrange
    - iotamixing
    # - ireturn
    # - lll
    - loggercheck
    # - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    - modernize
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    # - tagliatelle
    - testableexamples
    # - testifylint
    # - thelper
    - tparallel
    - unconvert
    # - unqueryvet
    # - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
  # Disable specific linters.
  disable:
    - asasalint
    - wsl
    - varnamelen
    - exhaustruct
    - wrapcheck
    - exhaustive
    - testpackage
    - revive
    - unused
    - unparam
    - tagliatelle
    - paralleltest
    - prealloc
    - noinlineerr
    - nestif
    - mnd
    - nosprintfhostport
    - lll
    - ireturn
    - iface
    - godox
    - err113
    - interfacebloat
    - funcorder
    - forcetypeassert
    - goconst
    - gocognit
    - gocyclo
    - gochecknoglobals
    - funlen
    - cyclop
    - maintidx
    - dupl
    - contextcheck
    - depguard
    - unqueryvet
    - testifylint
    - thelper
    - nonamedreturns
    # Disable overly strict style linters
    - godot          # Too strict about comment punctuation
    - nlreturn       # Too strict about blank lines before returns
    - godoclint      # Too strict about godoc formatting
    - inamedparam    # Too strict about interface parameter names
    - containedctx   # Sometimes necessary for certain patterns
    - predeclared    # Too strict about using predeclared identifiers
    - noctx          # Too strict about context parameter requirements
    - gochecknoinits # Init functions are acceptable for registration patterns
    - wsl_v5         # Too strict about whitespace (superseded by gofmt)
    - mirror         # Too strict about string builder usage
    - dupword        # Too strict about duplicate words in comments
    - nilnil         # Sometimes returning nil, nil is valid (optional pattern)
    - gocritic       # Too many opinionated suggestions
    - intrange       # Go 1.22+ feature, may have side effects
    - modernize      # Too opinionated about Go 1.22+ features
    - ineffassign    # Sometimes ineffectual assignments are intentional
    - goprintffuncname # Sometimes Error functions without 'f' suffix are valid
    - perfsprint     # Too opinionated about string performance optimizations

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true
    # Predefined exclusion rules.
    # Default: []
    paths:
      - examples/
      - farp-rust/
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    # Excluding configuration per-path, per-linter, per-text and per-source.
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - errorlint
      # Allow fmt.Print* in dev server, example, assets, and CLI files (build/dev tools)
      - path: (devserver\.go|example/|assets/|cli/)
        linters:
          - forbidigo
      # Allow file permissions 0644 in assets and CLI (build/dev tools, not secrets)
      - path: (assets/|cli/)
        linters:
          - gosec
        text: "G306"
      # Exclude some `staticcheck` messages.
      - linters:
          - staticcheck
        text: "SA9003:"
      # Exclude De Morgan's law simplification (style preference)
      - linters:
          - staticcheck
        text: "QF1001"
      # Exclude websocket library deprecation warnings (library migration outside linting scope)
      - linters:
          - staticcheck
        text: "websocket"
      # Exclude nil pointer dereference warnings in test files that have explicit nil checks
      - path: _test\.go
        linters:
          - staticcheck
        text: "SA5011"
      # Exclude `lll` issues for long lines with `go:generate`.
      - linters:
          - lll
        source: "^//go:generate "


issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues created after git revision
  # new: true
  # new-from-rev: HEAD

  # Independently of option `exclude` use or not the default list of exclusions
  # exclude-use-default: false

  # Fix found issues (if it's supported by the linter)
  fix: false

linters-settings:
  forbidigo:
    # Forbid the following identifiers (list of regexp).
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
    # Exclude godoc examples from forbidigo checks.
    # Default: true
    exclude-godoc-examples: true
    # Instead of matching the literal source code, use type information to replace
    # identifiers with fully qualified names.
    # Default: true
    analyze-types: true

  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: true

  errchkjson:
    # Issue on struct encoding that doesn't have exported fields.
    # Default: false
    report-no-exported: false

  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  gosec:
    # Exclude generated files
    # Default: false
    exclude-generated: true

  varnamelen:
    # The longest distance, in source lines, that is being considered a "small scope".
    # Variables used in at most this many lines will be ignored.
    # Default: 5
    max-distance: 10
    # The minimum length of a variable's name that is considered "long".
    # Variable names that are at least this long will be ignored.
    # Default: 3
    min-name-length: 2

  goimports:
    local-prefixes: github.com/xraph/forgeui

  gofumpt:
    extra-rules: true

severity:
  default: error
  rules:
    - linters:
        - dupl
        - gocyclo
        - lll
      severity: warning

